name: Build
#test
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer CMake
        run: cmake -B build

      - name: Compiler le projet
        run: cmake --build build
